### ISSUE TITLE
Add docs on how to contribute to the website

### ISSUE THREAD

**Issue by wooorm** [get-alex/alex#198]
### Subject of the issue

There are some issues with the website that could use some help, but there’s no documentation detailing on to work on the website.

### Steps to reproduce

1. Go to [`contributing.md`](https://github.com/get-alex/alex/blob/master/contributing.md)
2. View the `Contributions` section

### Expected behaviour

There should be a section detailing website contributions there. Something saying that the website is on the `website` branch, and that changes to `src` are automatically build to the `dest` folder.

### Actual behaviour

There is no such section 😢

**Comment by devkant** [comment]
I would like to do it

**Comment by wooorm** [comment]
Hi @devkant, thanks for offering! I suggest waiting for october 1st, so as to participate in hacktoberfest if you’re into that. But yeah, feel free to take a stab at it now, and let us know if you need help.

**Comment by hiteshpr** [comment]
HI, can I work on this?

**Comment by wooorm** [comment]
@hiteshpr Let’s wait for @devkant, he responded first!

**Comment by wooorm** [comment]
@devkant Not sure if @hiteshpr Is still working on this, so feel free to take a stab at it. Or anyone else :)
