### ISSUE TITLE
Add a note about hacktoberfest to the website

### ISSUE THREAD

**Issue by wooorm** [get-alex/alex#199]
### Subject of the issue

The repo for alex has a badge, and there’s some [issues](https://github.com/get-alex/alex/labels/hacktoberfest), but there’s nothing on the website.

### Steps to reproduce

Go to [the website](https://alexjs.com)

### Expected behaviour

There should be something about hacktoberfest there. Maybe something small, or maybe we could colour the background orange?

### Actual behaviour

There is no such reference to hacktoberfest 😢

**Comment by cunhazera** [comment]
@wooorm could I put some note at the Contributing section?

**Comment by wooorm** [comment]
Hey @cunhazera! Do you mean https://github.com/get-alex/alex/issues/198?

**Comment by cunhazera** [comment]
@wooorm Oh, no. I did not know about that issue.

**Comment by wooorm** [comment]
No problem, feel free to help out with that one!

**Comment by AidenMead** [comment]
Hey! I was hoping maybe I could add a little something for this issue? I was thinking something minimalist (to stick with the over-all style) but something to make sure people know about the Hacktoberfest contribution options. 

Would that be okay?

**Comment by wooorm** [comment]
Hi @AidenMead, yes, that would be great! I’d love a PR, and make sure to share your progress early. I think this issue could be fixed in many different ways, so let’s talk about it when you have something we can discuss.

And feel free to ask us for any tips :)

**Comment by strongSoda** [comment]
Hey there, I would like to help on this issue. Can I get started on it?

**Comment by tmott13** [comment]
I created a pull request for this issue 👍
