### ISSUE TITLE
Add support for HTML as an input language

### ISSUE THREAD

**Issue by wooorm** [get-alex/alex#201]
This issue is a bit bigger and harder than most others, but I think it would be quire valuable.

Similar to how [remark](https://github.com/remarkjs/remark) is used as a basis for markdown, we could use [rehype](https://github.com/rehypejs/rehype) for HTML!

**Comment by wooorm** [comment]
I don’t think so, but I don’t know.
But maybe it works to split this up, e.g., someone work on the API (`index.js`), someone else on the docs, someone on the CLI, etc. If someone starts, we can open new issues for the other parts.

**Comment by strongSoda** [comment]
I would look into the API part.

**Comment by riley-martine** [comment]
Since I didn't see any forks, I started over at https://github.com/riley-martine/alex

If anyone who actually knows Javascript could review [what I've done so far](https://github.com/riley-martine/alex/commit/437d07546fed324350fecc20e6a2ddeecd147446), I would appreciate it.

**Comment by wooorm** [comment]
Thanks @riley-martine. Could you create a PR for that? That makes it easier to review :)

What I didn’t mention before, is that an HTML processor should ignore all stuff that is not readable text. I think we should ignore things in `<script>`s or `<style>`s for example.

Another thing: If both markdown and HTML are in the default globs, we need to check files to see if they are either Markdown or HTML (potentially from the extensions again). Or maybe there should be a `--html` mode that just looks for `.htm`, `.html` files, and not markdown (and a `--markdown` flag for the other way round? 🤔)

**Comment by wooorm** [comment]
Alright, we’ve got the CLI! Now we need the same functionality for the API, docs, and better tests. Anyone up for helping with those?
