### ISSUE TITLE
Investigate sentiment detection

### ISSUE THREAD

**Issue by wooorm** [get-alex/alex#208]
### Subject of the issue

One thing alex lacks, is that it doesn’t detect very negative (but not profane) sentiment. There’s no place for that in docs, and maybe alex should check for negative sentiment as well.

### Potential behaviour

Maybe we could use something like [`retext-sentiment`](https://github.com/retextjs/retext-sentiment).

Supersedes GH-196.

**Comment by erickzhao** [comment]
Hey, that sounds like a really interesting idea. I've seen something similar used in a [GitHub app](https://probot.github.io/apps/sentiment-bot/) before, but they were using [Perspective API](https://github.com/retextjs/retext-sentiment) instead, which seemed to target conversational sentiment. Not sure how much of a difference that would make?

Is this an issue that needs more investigating in general, or would you be accepting PRs to test it out?

**Comment by wooorm** [comment]
Hi @erickzhao 👋

This is still a very vague issue, but awesome that you’re interested!
We came up with it in #196, but we’re not entirely sure whether it’s useful or feasible.

The perspective API is super interesting! I’m not sure if we should send all docs over the network though. And I’m not sure about the fact that it focusses on comments, and whether it would work for us.

A first step could be to paste some readmes and docs of popular projects into the [online demo](http://retextjs.github.io/retext-sentiment/).

A second, could be to drop retext-sentiment into a pipeline, e.g., something like this:

```js
var processor = unified()
  .use(remarkParse)
  .use(remark2retext)
  .use(sentiment)
  .use(plugin)

processor.runSync(processor.parse(doc), function (err, file) {
  console.error(vfileReporter(err || file))
})

function plugin() {
  // check all paragraphs, detect very negative ones, and emit a message about them
}
```

...run that over a few big projects, and see whether it works?

**Comment by swastikbanerjee07** [comment]
Hi ! How about using nltk for sentiment analysis by textblob API?
Can I take this issue up?

**Comment by erickzhao** [comment]
@swastikbanerjee07 feel free right now I haven't had the time over the past week to do anything!

**Comment by wooorm** [comment]
@swastikbanerjee07 This project is in JavaScript, but that could definitely be another project!

**Comment by swastikbanerjee07** [comment]
@wooorm Ou. Then I guess I'll not be able to contribute for this project? :( I don't know JavaScript.

**Comment by wooorm** [comment]
If someone wants to work on this, it can happen in a different retext plugin, in which case we can then check if it makes sense adding it here!
