### ISSUE TITLE
Investigate a “machine-learned” algorithm

### ISSUE THREAD

**Issue by wooorm** [get-alex/alex#209]
### Subject of the issue

alex, through retext-equality and retext-profanities, currently checks for words. But maybe it’s possible to teach it, through a big pile of “good” and “bad” texts, to learn whether texts are desired (or not).

Supersedes GH-196.

**Comment by wooorm** [comment]
Note that there are some bad examples of racist algorithms. I’m doubtful if this would work.

**Comment by swastikbanerjee07** [comment]
Hi ! Can I take this issue up?

**Comment by Qix-** [comment]
@swastikbanerjee07 absolutely :)

**Comment by swastikbanerjee07** [comment]
Cool! I'll start working on it.

**Comment by wooorm** [comment]
Closing this, it’s an interesting idea and can live next to the current alex. If someone wants to work on it, feel free!
