### ISSUE TITLE
Suggestion: add…

### ISSUE THREAD

**Issue by IfeanyiEkperi** [get-alex/alex#221]
##Too much negative whitespace on the footer

The footer segment is too large on mobile.

There is too much negative whitespace on the footer. Consider reducing the WHITESPACE to fit text

**Comment by Murderlon** [comment]
Hi @IfeanyiEkperi, thanks for the issue! However, It seems this comes down to opinionated styling. All the `section`'s deliberately have `min-height: 100vh` which means every `section` will take up your entire screen. As it seems this was the original intend, I'd consider this a non-issue. :)

**Comment by IfeanyiEkperi** [comment]
Ok @Murderlon. Noted
