### ISSUE TITLE
Add functionality to down arrow on landing page

### ISSUE THREAD

**Issue by laurenmayers** [get-alex/alex#223]
### Subject of the issue

Add functionality to white down arrow on landing page view so that the page scrolls down to content when clicked:

<img width="650" alt="screen shot 2018-10-08 at 10 44 33 am" src="https://user-images.githubusercontent.com/35752699/46615811-2c0b6300-cae7-11e8-8049-e268350230f1.png">

### Your environment

*   MacOS 10.14
*   Node v8.11.3 and npm v6.4.1, Chrome v69.0.3497.100

### Steps to reproduce

I will create a click event on the down arrow element so that the page scrolls to content.section

### Expected behaviour

The page scrolls to content when down arrow is clicked.

### Actual behaviour

Nothing happens when down arrow is clicked.

I would like to be assigned to this issue and start working on it if I can.

**Comment by Murderlon** [comment]
@laurenmayers seems like a perfect first issue to pick up here 👍

Do you already have an approach an mind? It could be as simple as an `<a href="#content">icon</a>` and a `<section id="content">...</section>`. If you are feeling adventurous, you could look into [`Element.scrollIntoView()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) as a [progressive enhancement](https://developer.mozilla.org/en-US/docs/Glossary/Progressive_Enhancement).

**Comment by laurenmayers** [comment]
I'll start with a simple anchor tag #content jump, and play around with the Element.scrollIntoView() function and see how it goes :)

**Comment by Murderlon** [comment]
resolved in #224
