### ISSUE TITLE
Add website favicon

### ISSUE THREAD

**Issue by laurenmayers** [get-alex/alex#225]
### Subject of the issue

Add a favicon to the website.

### Your environment
MacOS 10.14
Node v8.11.3 and npm v6.4.1, Chrome v69.0.3497.100

### Steps to reproduce
Add a favicon.png to the HTML head. 

### Expected behaviour
Favicon is displayed on desktop and mobile browsers (e.g. when saved as mobile bookmark). 

### Actual behaviour
No favicon has been added yet. 

I can add this and push this quickly if you're into this idea and this design - here is what I'm thinking of adding (even as a placeholder if you'd like a different design eventually): 

<img width="172" alt="favicon" src="https://user-images.githubusercontent.com/35752699/46684415-becc0080-cbc0-11e8-90cb-1b9a0015c468.png">

**Comment by Murderlon** [comment]
Sounds good 👍 
I'd recommend creating a 260x260 version and [this](https://realfavicongenerator.net/) online tool, which also generated the HTML for you.

**Comment by laurenmayers** [comment]
Thanks @Murderlon! That is an awesome tool. Just created the PR - looks like it's included my recent commits as part of a changelog, hoping I haven't PR'd those again too? (Still new to this, really appreciative of any feedback and wanting to make sure I'm contributing the right way). Thanks :)

**Comment by sebassdc** [comment]
Is this still required?
