### ISSUE TITLE
Contributing segment of the website

### ISSUE THREAD

**Issue by IfeanyiEkperi** [get-alex/alex#228]
The 'contributing' segment of the website has a little error.

'.....  You can also tweet to me or send me an e-mail.'

This should be:
.  You can also tweet at me or send me an e-mail.'

Secondly, there should be an email opt-in form on the website. We also need a form of mailing services to help keep volunteers updated with happening in the project as well as notify them when help is needed.

Some people don't usually visit GitHub often and a soft email reminder of open issues that needs attention would help. This would also help know the number of volunteers helping in the project. For records purposes.

**Comment by Murderlon** [comment]
@IfeanyiEkperi I like your enthusiasm in coming up with issues, but an email service for updates and issues is redundant and very time consuming. The single source of truth for issues are the [issues](https://github.com/get-alex/alex/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc), and updates feel like [release notes](https://github.com/get-alex/alex/releases).

If you like to contribute for hacktoberfest, I'd recommend checking out [this](https://github.com/search?l=JavaScript&q=label%3Ahacktoberfest+state%3Aopen+type%3Aissue&type=Issues) list, or `alex`'s issues or the issues in it's dependencies 🙂

**Comment by IfeanyiEkperi** [comment]
What of the grammatical error on the page?
