### ISSUE TITLE
Improving API documentation readability

### ISSUE THREAD

**Issue by MauroCoppola** [get-alex/alex#232]
### Subject of the issue

I saw that the README.md file also contains documentation for APIs but, unlike Table of Contents, it seems there isn't a clear separation between each explained API. That might make the navigation a bit less intuitive. Some ideas to improve it may be:

- Bulleted/numbered list for APIs;
- Indentation for API explaination;
- Dedicated .md file for API documentation;
- Particular style for API title to avoid misunderstanding with document's headers.

[remark]: https://github.com/remarkjs/remark

[retext]: https://github.com/retextjs/retext

[equality]: https://github.com/retextjs/retext-equality

[profanities]: https://github.com/retextjs/retext-profanities

**Comment by wooorm** [comment]
@MauroCoppola Hello, nice to e-meet you! I like most of these ideas! But could you expand on the below points?

> Indentation for API explaination;

I’m not sure what you mean with this 🤔

> Dedicated .md file for API documentation;

Hmm, wouldn’t that make it harder to find stuff?

> Particular style for API title to avoid misunderstanding with document's headers.

Don’t we already have that?

**Comment by wooorm** [comment]
@MauroCoppola What do you think about my previous comment? Anything I can clarify?

**Comment by bu7ch** [comment]
Can i take that.

**Comment by wooorm** [comment]
@MauroCoppola Ping!

@bu7ch I’m not sure yet whether this is an actionable issue.

**Comment by MauroCoppola** [comment]
@wooorm Sorry for my late response.

> Indentation for API explaination;
> I’m not sure what you mean with this 🤔

and

> Particular style for API title to avoid misunderstanding with document's headers.
> Don’t we already have that?

Those were some ideas to make a visual separation for each API explaination. For example, imho the *Integrations* paragraph seems a part of `alex.text(value)` API at first sight.

> Dedicated .md file for API documentation;
> Hmm, wouldn’t that make it harder to find stuff?

Adding a link to the documentation inside README.md might avoid the problem. In addition, creating a dedicated file can be useful for the future if more APIs and/or more documentation for each of those will be added.

**Comment by Murderlon** [comment]
non-issue as currently presented
