### ISSUE TITLE
Recursive File Matching

### ISSUE THREAD

**Issue by JWO719** [get-alex/alex#234]
### Subject of the issue

The RxJS Docs make use of a nested folder structure, to handle multiple files in a structured way. 
E.g. 
* /docs
* /docs/guides/beginner
* /docs/guides/intermediate
...

For now it seems like Alex just uses the root folder for linting. I'm not sure if there is already a recursive option in the cli or a support for folder "wildcards" like `alex content/**/*.md`. If not I would like to add one of those two options.

### Your environment

*   latest version of Alex

**Comment by wooorm** [comment]
Thanks for the issue @JWO719! Luckily globs are already supported! 😉

**Comment by JWO719** [comment]
Ok thanks for pointing that out, but I'm still slightly confuse, because the example above `alex content/**/*.md` in my case just lints the first folder inside the content folder. It neither checks the content folder itself, nor deeper levels e.g. 'content/guide/v6'. Am I doing something wrong? :D

**Comment by wooorm** [comment]
Could you try quoting the glob (`alex "content/**/*.md"`)? There’s differences in glob support on different platforms (mostly windows is weird).

**Comment by JWO719** [comment]
Yeah it is a linux based system but yeah quotes fixed it :D thanks a lot!
