### ISSUE TITLE
Change name

### ISSUE THREAD

**Issue by ParzivalWolfram** [get-alex/alex#242]
The repo is all about making things equal, but it uses a male name. Why? This is counter-intuitive, you trigger me.

**Comment by toloveru** [comment]
This repository is so predominantly male, that's so damn offensi🅱️e!!! Change its name right now because I'M OFFENDED and I'm entitled to enforcing the name change of projects that I haven't contributed to, for "protecting" minorites that I've never even met, because REASONS!!! 😆

**Comment by toloveru** [comment]
And how dare you try think otherwise, you misogynistic cis make a-hole?! I'ma expose you on Twitter if you don't change your name RIGHT NOW!!! 😡

**Comment by wooorm** [comment]
[alex is not a male name](https://github.com/get-alex/alex/tree/25cdc8659370cbe1427d248b3c7828ad9db4bda5#why-is-this-named-alex).
