### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by chintan9** [get-alex/alex#245]
[This package](https://www.jsdelivr.com/package/npm/alex) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by wooorm** [comment]
You can go to [releases](https://github.com/get-alex/alex/releases) to get a built browser version.
There are also alternatives to jsdelivr around that do the building with browserify/webpack that you could use!
