### ISSUE TITLE
(optionally) add links with further explanations

### ISSUE THREAD

**Issue by lsmith77** [get-alex/alex#247]
some people might not be aware of why something is problematic (“guys”) or what discussions have taken place in other communities (master/slave). so it may make sense to start attaching links to suggestions with recommendations for further reading and context.

**Comment by wooorm** [comment]
Totally!

You can pass the `--why` flag to get that information.

We don’t have much information yet though, but would appreciate more notes and sources. You can add them [`retext-equality`](https://github.com/retextjs/retext-equality), [for example like so](https://github.com/retextjs/retext-equality/blob/5e70c966140ccd6910956c3762c7bbe55dd844de/script/ablist.yml#L15-L23), and when added there automatically show up here! We’d appreciate the help!

**Comment by lsmith77** [comment]
sweet
