### ISSUE TITLE
Linting isolating words like simple or easy

### ISSUE THREAD

**Issue by carolstran** [get-alex/alex#253]
👋 👋 👋 

First of all, I ❤️ alex and the work that you do so thank you!

I had a quick question regarding the words that are caught via alex. Specifically, I've been trying to remove isolating words (easy, simple, just, obviously, etc) from documentation. Many people have suggested that I add these words to alex because that's a linter they are already using. Would you be open to this? I would classify these words as insensitive, but they aren't in the same realm as profanity, racial slurs, etc. or fit perfectly into any existing retext plugins that I know of. 

No pressure either way, I'm just curious if this is something you've considered (though of course if you would be interested, I'd be happy to help) 😇 

Let me know if you want more context and again, thank you for creating such a great tool.

**Comment by wooorm** [comment]
Yes that’s great! This is something already in `retext-equality (https://github.com/retextjs/retext-equality/commit/24f12addfaff7cecb989c6cc521ca53cf8ba59bd), but I haven’t touched much of alex in a while (a year?! since last hacktoberfest?! 🎃).

Are there words, except the ones already added there, that you’d like to see checked?

**Comment by carolstran** [comment]
Oh this is excellent! Sorry I completely didn't think to look in `retext-equality` 🤦‍♀ 

The only addition to the ones already there would be some of the variations - for example: `easily`, `simple` and `obvious`

Forgot to mention, part of the reason I asked is that I'm thinking of making an alex plugin for Gatsby (unless you already know if one but I didn't see anything in the plugin library) and wanted to make sure that it catches these types of words as well 💞

**Comment by wooorm** [comment]
Oh don’t worry, I’ll make the contribution docs clearer about that today as well!

Can you do a PR to retext- equality with those words? ✨ we can publish that before a new version of alex goes live later today!

P.s. I don't know of a gatsby alex plugin, good idea 👍

**Comment by carolstran** [comment]
Yes I can but I don't know if I'll have time until later this evening ahhhhhhh I'll see what I can do 👩‍🏭

**Comment by wooorm** [comment]
Ohh yeah sorry no rush! It can wait!

**Comment by carolstran** [comment]
@wooorm https://github.com/retextjs/retext-equality/pull/85

**Comment by wooorm** [comment]
Fixed in [`retext-equality@4.2.0`](https://github.com/retextjs/retext-equality/releases/tag/4.2.0), thank you!
