### ISSUE TITLE
Clarity of language around what alex checks for, in README

### ISSUE THREAD

**Issue by BNewing** [get-alex/alex#267]
In the README, there is the following text:

> alex checks things such as:
> - Gendered work-titles, such as suggesting garbage collector for garbageman and proprietor for landlord
> - Gendered proverbs, such as suggesting bravely for like a man, or courteous for ladylike.
> - Ablist language, such as suggesting person with learning disabilities for learning disabled
> - Condescending language, such as warning for obviously, everyone knows, etc
> - Intolerant phrasing, such as suggesting primary and replica instead of master and slave
Profanities, such as butt 🍑

I don't know if it's just me, but it took me a couple of read throughs to understand fully what it meant. 'alex checks things such as gendered work-titles' makes sense on it's own. But suggesting something is slightly separate to checking, and it took me a few read-throughs to get what it was saying. It was only when I went to look at the table view that's linked that it clicked which of the two suggested things were the suggestions from alex, and what it was replacing.

I'm not sure what it could be changed to - I'm not the best with words, and I'm sure this explanation could be clearer too!  One thing that could be done is listing what it suggests as a separate list/table on the README. Just one thought :)

**Comment by wooorm** [comment]
How about this?

```markdown
**alex** checks things such as:

*   Gendered work-titles (if you write `garbageman` alex suggests `garbage collector`; if you write `landlord` alex suggests `proprietor`)
*   Gendered proverbs (if you write `like a man` alex suggests `bravely`; if you write `ladylike` alex suggests `courteous`)
*   Ablist language (if you write `learning disabled` alex suggests `person with learning disabilities`)
*   Condescending language (if you write `obviously ` or `everyone knows` alex warns about it)
*   Intolerant phrasing (if you write `master` and `slave` alex suggests `primary ` and `replica`)
*   Profanities (if you write `butt` 🍑 alex warns about it)

…and much more!

Note: alex assumes good intent: that you don’t mean to offend!
```

**Comment by BNewing** [comment]
Looks good to me :D
