### ISSUE TITLE
Is this project an ironic take on being politically correct?

### ISSUE THREAD

**Issue by fdenzer** [get-alex/alex#283]
Since alexjs proposes many complicated words that are not fit for production,
(some SAP developers and me decided that for ourselves, not an official statement of
my employer or aforementioned company)

- Is this project meant to be sincere? If yes:
- Are some terms like master/slave replication not the same as primary/replica in some contexts, as my fellow devs claim? Primary replica is probably about sharding instances, while offline or off-site locations store "slave" backups, supposedly.

If I were to guess, "cripple" in the linux kernel *never* means "person with a limp", so I guess I just spoiled this module by revealing it to be an in-joke on exaggerated anticipatory obedience. 🤷🏽‍♀️

**Comment by wooorm** [comment]
https://wooorm.com/blog/alex/
