### ISSUE TITLE
Needs better context support

### ISSUE THREAD

**Issue by boyter** [get-alex/alex#284]
### Subject of the issue

Consider the following,

```
I want to visit Niger. Jessie (top girl!) recons its great place to practice kung fu.
```

### Your environment

Just tried it on the demo site actually.

### Steps to reproduce

Enter,

```
I want to visit Niger. Jessie (top girl!) recons its great place to practice kung fu.
```

Observe the output.

### Expected behaviour

Nothing should actually be picked up. Niger is a place (perhaps check for upper-case first letter?). Girl in this situation or kid or child would actually be insulting to Jessie which admittedly is hard because its one of those tricky names. Fu probably needs to have some sort of check if if has kung just before it.

### Actual behaviour

It flags the following 

```
1:17-1:22 Don't use Niger, it's profane
1:36-1:40 girl may be insensitive, when referring to a person, use kid, child instead
1:36-1:40 Be careful with girl, it's profane in some cases
1:83-1:85 Don't use fu, it's profane
```

**Comment by wooorm** [comment]
Hi there!

alex indeed doesn’t have context: you as a human do. Natural language is not code. alex is about finding potential stuff, and you can do with that what you want. [See also other issues that mention the word context](https://github.com/get-alex/alex/search?q=context&type=Issues), and see the [Control](https://github.com/get-alex/alex#control) and [Configuration](https://github.com/get-alex/alex#configuration) sections in the readme. If you don’t care about profanities, set `profanitySureness: 2`, and if you believe the ratings in these examples are incorrect, a suggestion issue or PR for them in [`words/cuss`](https://github.com/words/cuss#api) is appreciated!
