### ISSUE TITLE
How to ignore the term “Special sets” which is a term of art in mathematics?

### ISSUE THREAD

**Issue by salutis** [get-alex/alex#302]
I have a LaTeX file with the following line:

```
\subsection{Special sets}
```

Alex complains:

```
salutis@Workstation discrete-mathematics % alex notes.tex
notes.tex
  86:13-86:20  warning  `Special` may be insensitive, use `Has a disability`, `Person with a disability`, `People with disabili
ties` instead  special  retext-equality

⚠ 1 warning
```

I created `~/.alexrc`:

```
salutis@Workstation discrete-mathematics % cat ~/.alexrc
{
        "allow": ["Special sets"]
}
```

Yet, Alex keeps complaining.

P.S. 1: I tried to move `.alexrc` to the working directory (`.`) but that did not help.
P.S. 2: Alex is installed via Homebrew using `brew install alexjs`.

How to ignore the term “Special sets”?

**Comment by AlisaLiso** [comment]
Hi @salutis! As I understand in the configuration file, for 'allow', you can use only the rules name. So you can allow rule:
```
{
  "allow": ["special"]
}
```
or you can disable rule for the file via comment.
I hope it help.

**Comment by wooorm** [comment]
Thanks Alisa! I believe that should answer your question, Rudolf, so I’ll close this!

**Comment by salutis** [comment]
@AlisaLiso Thank you Alisa, it works! 💚
