### ISSUE TITLE
Request workspace/executeCommand failed

### ISSUE THREAD

**Issue by aaronfranke** [get-alex/alex#310]
### Subject of the issue

When I try to run AlexLinter, I get this error message:

```
[Error - 1:06:34 PM] Request workspace/executeCommand failed.
  Message: Request workspace/executeCommand failed with message: Cannot read property 'uri' of undefined
  Code: -32603 
```

### Your environment

*   **OS**: Linux (Ubuntu-based, 64-bit)
*   **Packages**: VS Code 1.52.1, Alex 0.6.5
*   **Env**: I don't think this is applicable.

### Steps to reproduce

1. Install Alex from VS Code, "AlexJS Linter `tlahmann.alex-linter`"
2. I noticed that it wasn't doing anything by itself. Not on plain text files, not on code files.
3. Press Ctrl+Shift+P
4. Select "AlexLiner: Check for insensitive, inconsiderate writing" (btw, "AlexLiner" is misspelled, should be "AlexLinter")
5. VS Code says "A request has failed. See the output for more information.
6. I get the error message in the output.

### Expected behaviour

It should work and not throw an error.

### Actual behaviour

I get this error message:

```
[Error - 1:06:34 PM] Request workspace/executeCommand failed.
  Message: Request workspace/executeCommand failed with message: Cannot read property 'uri' of undefined
  Code: -32603 
```

**Comment by wooorm** [comment]
Hi there!

This sounds like a VSCode related issue, not something with the core of Alex.

I do maintain Alex, but not the VSCode extension. So I have no knowledge of how that works, and it sounds like it can’t be fixed in this project. Perhaps ask the folks of `tlahmann.alex-linter`?

Happy holidays!
