### ISSUE TITLE
Can we talk about context

### ISSUE THREAD

**Issue by mikeysan** [get-alex/alex#311]
I would like to know if this is the best place to ask about the issue of context?

We have implemented AlexJS in our Discord Bot and it works great. I do, however, have an issue with a context that keeps getting me and others warned. Here's an example.

```sh
user1: I like your display image. Where is it from?
user2: Oh thanks. My daughter drew that.
user1: Not sure how to respond
user2: gets a warning.
```

I believe because user2 is talking about their own child as indicated by "my", "daughter" in this instance should not be flagged as insensitive. Therefore, I would like to know where is the best place to address the issue of "context"?

**Comment by wooorm** [comment]
Hi Mike! You raise a valid point! alex has no knowledge of context; I intended it to be used on technical docs, theses, readmes and so, definitely not on fiction or when texting friends.

I would not suggest using alex in slack or discord. If you really want to, it should be configured, probably with a list of things to [deny](https://github.com/get-alex/alex#configuration).

> Therefore, I would like to know where is the best place to address the issue of "context"?

“Solving” context would mean machine learning and I think that’s a dangerous path.
I do think this issue https://github.com/get-alex/alex/issues/285 could help there though?

**Comment by mikeysan** [comment]
Okay. Thanks for letting me know.
