### ISSUE TITLE
eslint-plugin-alex

### ISSUE THREAD

**Issue by bbbryan14** [get-alex/alex#312]
### Subject of the feature

It'd be great to use alex as linting rules.

### Alternatives

I started a eslint plugin repo https://github.com/bbbryan14/eslint-plugin-alex . My gig is currently using it but it'd be great to transfer ownership and be properly maintained. It has not been published to npm yet.

**Comment by wooorm** [comment]
Hi, cool that you’re working on this!
Moving it to this org probably means that I’ll have to maintain it for years to come, and I’m not too sure about that (I don’t use ESLint directly myself). 😬
It should definitely be added to the [list of integrations](https://github.com/get-alex/alex#integrations) when it’s released though!

**Comment by bbbryan14** [comment]
sounds good, I made that repo private for now. I spoke with the manager and to see if we can dedicate some more time to the project to have it in a good enough state to release it. I'll reach out once it's released. 

Closing this issue.

**Comment by mepsteinpear** [comment]
@bbbryan14  I was looking into starting a similar project would it be possible for me to get access to your repo? Thanks!
