### ISSUE TITLE
Support for dropbox and google docs

### ISSUE THREAD

**Issue by PhilzAce1** [get-alex/alex#316]
### Subject of the feature
the concept of Alex is really nice 🔥 , but It will be better if we could get support for other writing platforms/ docs like google docs and Dropbox paper

Describe your issue here.

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen?  Please describe the desired behaviour.

### Alternatives

What are the alternative solutions?  Please describe what else you have considered?

**Comment by wooorm** [comment]
> the concept of Alex is really nice 🔥 

Thank you!

> but It will be better if we could get support for other writing platforms/ docs like google docs and Dropbox paper

There are already many integrations maintained by the community: https://github.com/get-alex/alex#integrations.
I think these ideas of yours could live there as well.

I’d gladly link to them, but I’m not personally interested in making them!
