### ISSUE TITLE
Confused about plural words

### ISSUE THREAD

**Issue by ali-habibzadeh** [get-alex/alex#317]
I tried the API by passing "Boys will be boys" and got nothing back. Does it only work when words are not plural?

**Comment by wooorm** [comment]
depends on what people’ve added. In this case only the singular is there: https://github.com/retextjs/retext-equality/blob/3ad26c587946f79547ddbf31b852929e3ea2a777/data/en/gender.yml#L34-L42.
A PR similar to that, which adds the plural, would be appreciated!

**Comment by kshamajain99** [comment]
@wooorm If you could take a look at this PR whenever time permits https://github.com/retextjs/retext-equality/pull/111.
