### ISSUE TITLE
Failed to build reviewdog/action-alex@v1

### ISSUE THREAD

**Issue by venkuppu-chn** [get-alex/alex#320]
### Subject of the issue
Build reviewdog/action-alex@v1 stage is failed. It seems like not able to reach the link mentioned below. 
https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz

**Error Log:**
  Step 4/8 : RUN apk --no-cache add git
   ---> Running in fbe6d6b3a6c6
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
  WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)
  fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
  WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)
  ERROR: unable to select packages:
    git (no such package):
      required by: world[git]
  The command '/bin/ash -eo pipefail -c apk --no-cache add git' returned a non-zero code: 1
  Warning: Docker build failed with exit code 1, back off 3.693 seconds before retry.

### Your environment

Github Action

### Steps to reproduce
Run below workflow
name: reviewdog
on: [pull_request]
jobs:
  alex:
    name: runner / alex
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-alex@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: github-pr-review
          level: warning

**Comment by wooorm** [comment]
Hi! This is not the place to ask questions or report bugs for reviewdog/action-alex.
