### ISSUE TITLE
Using Alex to check user text in a html input or textarea element

### ISSUE THREAD

**Issue by charklewis** [get-alex/alex#327]
I am thinking of using this package to link a html input / textarea element as a user is typing in a react app. I couldn't see any tutorials or suggestions in the repo that this is supported. It just looks like a cli tool. 

Is there a way of using Alex to import into a React app and check text programatically?

**Comment by wooorm** [comment]
sure, the [readme describes how to use the aPI](https://github.com/get-alex/alex#api) and [the website also uses alex](https://github.com/get-alex/alex/blob/website/src/index.js)
