### ISSUE TITLE
Suggestion: Suggest 'main' as a replacement for 'master'

### ISSUE THREAD

**Issue by zaneshaw** [get-alex/alex#331]
I think using 'main' as an alternative replacement for 'master' would be a good idea as GitHub themselves have migrating to using this term from the latter.

**Comment by Murderlon** [comment]
Hi, I don't understand the issue, this repo already uses the `main` branch and Alex runs on files, it doesn't check git branches. If you mean raising a warning on "master" and suggesting "main", I don't think that's a good idea as people aren't necessarily talking about branches and there are already multiple "master" related rules.

**Comment by zaneshaw** [comment]
That's alright. I just saw 'main' as comparable to the already existing usage of 'primary'.
