### ISSUE TITLE
The word 'remain' is considered profane

### ISSUE THREAD

**Issue by J4000** [get-alex/alex#336]
Checking a file or text with the word 'remain' produces the following warning:
> Be careful with `remain`, it’s profane in some cases

This can be seen on the demo site:

![screenshot](https://user-images.githubusercontent.com/7039105/202902499-3093f8de-17ae-4d92-a684-3e28a8b780ce.png)

Is this true? I couldn't find anything about it on the Internet when searching.

**Comment by wooorm** [comment]
Thanks! No, this “singular” is fine. The message is supposed to be for `remains`.

**Comment by 402010salim** [comment]
Okey
