### ISSUE TITLE
Files without file extension are not included for linting

### ISSUE THREAD

**Issue by tymonx** [get-alex/alex#338]
### Subject of the issue

Files without file extension are not included for linting. Example: `README`.

### Your environment

*   **OS**: `podman`
*   **Packages**: `podman run -it --rm registry.gitlab.com/pipeline-components/alex:0.21.9 --version`

```plaintext
11.0.0
```

*   **Env**: `podman run -it --rm registry.gitlab.com/pipeline-components/alex:0.21.9 env`

```plaintext
NODE_VERSION=19.8.1
YARN_VERSION=1.22.19
```

### Steps to reproduce

1. Create file without file extension:

```plaintext
echo "pop" > README
```

2. Run `alex`:

```plaintext
podman run -it --rm --volume "$(pwd):/alex:ro,z" --workdir "/alex" registry.gitlab.com/pipeline-components/alex:0.21.9 --why .
```

### Expected behaviour

It should return status code `1` and print:

```plaintext
README
  1:1-1:4  warning  `pop` may be insensitive, use `parent` instead  dad-mom  retext-equality

⚠ 1 warning
```

### Actual behaviour

It returns status code `0` (success) without printing anything to standard output or error output.

### Workaround

Explicitly provide files without file extension to alex:

```plaintext
podman run -it --rm --volume "$(pwd):/alex:ro,z" --workdir "/alex" registry.gitlab.com/pipeline-components/alex:0.21.9 --why README
```

But this will not work when `.alexignore` is defined:

```plaintext
echo "README" > .alexignore
```

It returns status code `1` and prints:

```plaintext
README
  1:1  error  Cannot process specified file: it’s ignored

✖ 1 error
```

### Related issues

- https://github.com/get-alex/alex/issues/170

**Comment by wooorm** [comment]
Hi!

It is intentional that files without extensions, which could include any code, or be for example binary files, are not included by default.

If you want to include certain files, pass them: `alex whatever`
