### ISSUE TITLE
Hidden files started with dot are not included for linting

### ISSUE THREAD

**Issue by tymonx** [get-alex/alex#339]
### Subject of the issue

Hidden files started with dot `.` are not included for linting. Example: `.hidden`.

### Your environment

*   **OS**: `podman`
*   **Packages**: `podman run -it --rm registry.gitlab.com/pipeline-components/alex:0.21.9 --version`

```plaintext
11.0.0
```

*   **Env**: `podman run -it --rm registry.gitlab.com/pipeline-components/alex:0.21.9 env`

```plaintext
NODE_VERSION=19.8.1
YARN_VERSION=1.22.19
```

### Steps to reproduce

1. Create hidden file that starts from dot `.`:

```plaintext
echo "pop" > .hidden
```

2. Run `alex`:

```plaintext
podman run -it --rm --volume "$(pwd):/alex:ro,z" --workdir "/alex" registry.gitlab.com/pipeline-components/alex:0.21.9 --why .
```

### Expected behaviour

It should return status code `1` and print:

```plaintext
.hidden
  1:1-1:4  warning  `pop` may be insensitive, use `parent` instead  dad-mom  retext-equality

⚠ 1 warning
```

### Actual behaviour

It returns status code `0` (success) without printing anything to standard output or error output.

### Workaround

Explicitly provide hidden files to alex (for example using shell glob pattern substitution `.*`):

```plaintext
podman run -it --rm --volume "$(pwd):/alex:ro,z" --workdir "/alex" registry.gitlab.com/pipeline-components/alex:0.21.9 --why .*
```

But this will not work when `.alexignore` is defined:

```plaintext
echo ".hidden" > .alexignore
```

It returns status code `1` and prints:

```plaintext
.alexignore: no issues found
.hidden
  1:1  error  Cannot process specified file: it’s ignored

✖ 1 error
```

### Related issues

- https://github.com/get-alex/alex/issues/170

**Comment by wooorm** [comment]
Hi!

It is intentional that dotfiles are not included by default.

If you want to include certain files, pass them: `alex .hidden`
