### ISSUE TITLE
Violation from URLs should be skipped because URL links cannot be changed

### ISSUE THREAD

**Issue by tymonx** [get-alex/alex#341]
### Subject of the issue

Violation from URLs should be skipped because URL links cannot be changed. Example:

```plaintext
https://www.freedesktop.org/software/systemd/man/systemd-analyze.html
```

It contains word `man`.

### Your environment

*   **OS**: `podman`
*   **Packages**: `podman run -it --rm registry.gitlab.com/pipeline-components/alex:0.21.9 --version`

```plaintext
11.0.0
```

*   **Env**: `podman run -it --rm registry.gitlab.com/pipeline-components/alex:0.21.9 env`

```plaintext
NODE_VERSION=19.8.1
YARN_VERSION=1.22.19
```

### Steps to reproduce

1. Create file with URL link:

```plaintext
echo "https://www.freedesktop.org/software/systemd/man/systemd-analyze.html" > README.md
```

2. Run `alex`:

```plaintext
podman run -it --rm --volume "$(pwd):/alex:ro,z" --workdir "/alex" registry.gitlab.com/pipeline-components/alex:0.21.9 --why .
```

### Expected behaviour

It should return status code `0` (success) without printing anything to standard output or error output.

### Actual behaviour

It returns status code `1` and prints:

```plaintext
README.md
  1:46-1:49  warning  `man` may be insensitive, use `people`, `persons`, `folks` instead  gals-man  retext-equality

⚠ 1 warning
```

**Comment by wooorm** [comment]
alex takes markdown (or MDX, or HTML) as input. I recommend using a markdown link around URLs: `[descriptive text](url)`.

**Comment by etrobert** [comment]
URLs can be changed by the owner (with some effort), it makes sense to me to bring up insensitive words in them.

The example brought up uses `man` as an abbreviation of `manual`, so it an unfortunate exception.

You could disable this rule for this line

```
<!--alex ignore gals-man-->
```

**Comment by wooorm** [comment]
Hey!

If you use markdown or HTML, you can use the markdown (or HTML) structures to turn links into links: `[descriptive text](the-url)`.

This is intentional: that we check prose. And that we don’t check syntax. Use the syntax provided by the markdown (or HTML) language and it works here!

Also agreeing with @etrobert that anything *could* be checked. If you want that, use `--text`!

Closing as you can use markdown/HTML syntax!
