### ISSUE TITLE
Add support for yaml and json file formats

### ISSUE THREAD

**Issue by savage-alex** [get-alex/alex#344]
### Subject of the feature

Have you considered extending the supported files list to YAML and json files? I really like this tool but would like to use it to ensure openAPI definitions are inclusive as well as text docs. I use codespellChecker on these to ensure there arent typos but having alex available too would be fantastic.

### Problem

Being able to lint openAPI definitions in YAML and JSON for uninclusive language  is hard

### Expected behaviour

Add support for JSON and YAML file formats.

### Alternatives

We have considered spectral with a word list

Thank you very much for this great project

**Comment by wooorm** [comment]
This project is about prose and YAML and JSON are not particularly about prose.
If JSON or so contains prose, different files would use prose in at different places. And would there be (markdown, html) markup in those strings?
It sounds like something that everyone would have different needs and requirements for. At which point: perhaps use the API for this? https://github.com/get-alex/alex#api

**Comment by savage-alex** [comment]
Great response thank you we will check that out.

It was the useage of those languages for openAPI that I was interested in. They contain long descriptions and summaries to help people understand the purpose and capabilities of an API. It is this part I would like to check over to ensure they are inclusive and equitable.
